# Generated by Django 4.0.1 on 2022-02-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('startDate', models.DateField(verbose_name='시작일')),
                ('endDate', models.DateField(verbose_name='종료일')),
                ('techStack', models.TextField(verbose_name='기술스택')),
                ('explain', models.TextField(verbose_name='내용')),
                ('imgSrc', models.ImageField(blank=True, null=True, upload_to='projectImg/', verbose_name='png이미지소스')),
                ('gifSrc', models.ImageField(blank=True, null=True, upload_to='projectImg/', verbose_name='gif이미지소스')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkName', models.CharField(max_length=50, verbose_name='링크명')),
                ('linkUrl', models.URLField(verbose_name='링크')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectLink', to='portfolio.project')),
            ],
        ),
    ]
