# Generated by Django 4.0.1 on 2022-01-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('startDate', models.DateField(verbose_name='시작일')),
                ('endDate', models.DateField(verbose_name='종료일')),
                ('techStack', models.TextField(verbose_name='기술스택')),
                ('explain', models.TextField(verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.user')),
            ],
        ),
    ]
